import React from 'react';
import {
  Users,
  FolderGit2,
  CalendarDays,
  BrainCircuit,
  AlertTriangle,
  FileSpreadsheet,
  Lightbulb,
  FileText,
  ArrowRight,
  ShieldCheck,
  Zap,
} from 'lucide-react';
import { AdminOverviewStats } from '../../types/index';

interface AdminOverviewProps {
  overview: AdminOverviewStats | null;
  onNavigateTab: (tab: any) => void;
  onOpenUpload?: () => void;
  onRunQuickPrediction?: () => void;
}

export const AdminOverview: React.FC<AdminOverviewProps> = ({
  overview,
  onNavigateTab,
  onOpenUpload,
}) => {
  const cards = [
    {
      id: 'users',
      title: 'Total Users',
      count: overview?.total_users ?? 0,
      icon: Users,
      color: 'text-indigo-600 bg-indigo-50 border-indigo-200',
      badge: 'RBAC Enforced',
      tab: 'users',
      desc: 'Registered Officers, Analysts, Viewers & Admin',
    },
    {
      id: 'projects',
      title: 'Total Projects',
      count: overview?.total_projects ?? 0,
      icon: FolderGit2,
      color: 'text-blue-600 bg-blue-50 border-blue-200',
      badge: 'Active Registry',
      tab: 'projects',
      desc: 'National infrastructure capital assets tracked',
    },
    {
      id: 'monitoring',
      title: 'Total Monitoring Records',
      count: overview?.total_monitoring_records ?? 0,
      icon: CalendarDays,
      color: 'text-emerald-600 bg-emerald-50 border-emerald-200',
      badge: 'Time-Series',
      tab: 'monitoring',
      desc: 'Monthly milestone & expenditure data points',
    },
    {
      id: 'predictions',
      title: 'Total Predictions',
      count: overview?.total_predictions ?? 0,
      icon: BrainCircuit,
      color: 'text-purple-600 bg-purple-50 border-purple-200',
      badge: 'ML Inferences',
      tab: 'predictions',
      desc: 'Calculated delay, cost overrun & risk scores',
    },
    {
      id: 'alerts',
      title: 'Total Alerts',
      count: overview?.total_alerts ?? 0,
      icon: AlertTriangle,
      color: 'text-amber-600 bg-amber-50 border-amber-200',
      badge: 'Early Warning',
      tab: 'alerts',
      desc: 'Threshold breaches & critical warning dispatches',
    },
    {
      id: 'datasets',
      title: 'Total Datasets',
      count: overview?.total_datasets ?? 0,
      icon: FileSpreadsheet,
      color: 'text-teal-600 bg-teal-50 border-teal-200',
      badge: 'Import Archives',
      tab: 'datasets',
      desc: 'CSV / Excel historical batches uploaded',
    },
    {
      id: 'recommendations',
      title: 'Total Recommendations',
      count: overview?.total_recommendations ?? 0,
      icon: Lightbulb,
      color: 'text-amber-500 bg-amber-50 border-amber-200',
      badge: 'Prescriptive',
      tab: 'recommendations',
      desc: 'Actionable remedial strategies generated by AI',
    },
    {
      id: 'activity',
      title: 'Total Activity Logs',
      count: overview?.total_activity_logs ?? 0,
      icon: FileText,
      color: 'text-rose-600 bg-rose-50 border-rose-200',
      badge: 'Immutable Audit',
      tab: 'activity',
      desc: 'Logged administrative operations & mutations',
    },
  ];

  return (
    <div className="space-y-6">
      {/* Top Banner */}
      <div className="bg-gradient-to-r from-slate-900 via-indigo-950 to-slate-900 text-white rounded-xl p-6 border border-slate-800 shadow-md">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <span className="px-2 py-0.5 text-xs font-semibold uppercase tracking-wider rounded bg-indigo-500/20 text-indigo-300 border border-indigo-500/30">
                Full Administrative Authority
              </span>
              <span className="text-xs text-slate-400">Database Source of Truth</span>
            </div>
            <h2 className="text-xl font-bold tracking-tight">Sentinel Central Administration Engine</h2>
            <p className="text-sm text-slate-300 max-w-2xl">
              Complete programmatic governance over all national project data, machine learning inference engines,
              monthly time-series submissions, user access privileges, and automated warning pipelines.
            </p>
          </div>
          <div className="flex flex-wrap items-center gap-2">
            {onOpenUpload && (
              <button
                id="btn-overview-upload-dataset"
                onClick={onOpenUpload}
                className="px-3.5 py-2 bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-medium rounded-lg transition-colors flex items-center gap-1.5 shadow-sm"
              >
                <FileSpreadsheet className="w-3.5 h-3.5" />
                <span>Upload Dataset</span>
              </button>
            )}
            <button
              id="btn-overview-nav-projects"
              onClick={() => onNavigateTab('projects')}
              className="px-3.5 py-2 bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-medium rounded-lg border border-slate-700 transition-colors flex items-center gap-1.5"
            >
              <FolderGit2 className="w-3.5 h-3.5 text-indigo-400" />
              <span>Manage Projects</span>
            </button>
          </div>
        </div>
      </div>

      {/* 8 Metric KPI Cards Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        {cards.map((c) => {
          const Icon = c.icon;
          return (
            <div
              key={c.id}
              id={`overview-stat-${c.id}`}
              onClick={() => onNavigateTab(c.tab)}
              className="bg-white rounded-xl p-5 border border-slate-200 hover:border-indigo-300 hover:shadow-md transition-all cursor-pointer group flex flex-col justify-between"
            >
              <div>
                <div className="flex items-center justify-between mb-3">
                  <div className={`p-2.5 rounded-lg border ${c.color}`}>
                    <Icon className="w-5 h-5" />
                  </div>
                  <span className="text-[11px] font-medium px-2 py-0.5 rounded-full bg-slate-100 text-slate-600">
                    {c.badge}
                  </span>
                </div>
                <div className="text-2xl font-bold text-slate-900 group-hover:text-indigo-600 transition-colors">
                  {c.count}
                </div>
                <div className="text-sm font-semibold text-slate-800 mt-0.5">{c.title}</div>
                <div className="text-xs text-slate-500 mt-1 leading-relaxed">{c.desc}</div>
              </div>

              <div className="mt-4 pt-3 border-t border-slate-100 flex items-center justify-between text-xs font-medium text-indigo-600 group-hover:translate-x-0.5 transition-transform">
                <span>View and manage</span>
                <ArrowRight className="w-3.5 h-3.5" />
              </div>
            </div>
          );
        })}
      </div>

      {/* Quick Access Matrix */}
      <div className="bg-white rounded-xl p-6 border border-slate-200">
        <h3 className="text-sm font-bold text-slate-900 uppercase tracking-wider mb-4 flex items-center gap-2">
          <Zap className="w-4 h-4 text-indigo-600" />
          <span>Administrative Control Modules</span>
        </h3>
        <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 gap-3">
          {[
            { label: 'Users', tab: 'users', count: overview?.total_users },
            { label: 'Projects', tab: 'projects', count: overview?.total_projects },
            { label: 'Monitoring', tab: 'monitoring', count: overview?.total_monitoring_records },
            { label: 'AI Predictions', tab: 'predictions', count: overview?.total_predictions },
            { label: 'Risk Factors', tab: 'risk-factors', count: null },
            { label: 'Recommendations', tab: 'recommendations', count: overview?.total_recommendations },
            { label: 'Alerts', tab: 'alerts', count: overview?.total_alerts },
            { label: 'Datasets', tab: 'datasets', count: overview?.total_datasets },
            { label: 'Model Engine', tab: 'models', count: null },
            { label: 'Audit Logs', tab: 'activity', count: overview?.total_activity_logs },
            { label: 'System Health', tab: 'status', count: null },
          ].map((item) => (
            <button
              key={item.tab}
              id={`quick-nav-${item.tab}`}
              onClick={() => onNavigateTab(item.tab)}
              className="p-3 text-left rounded-lg bg-slate-50 hover:bg-indigo-50 border border-slate-200 hover:border-indigo-200 transition-colors group"
            >
              <div className="text-xs font-semibold text-slate-800 group-hover:text-indigo-700">
                {item.label}
              </div>
              {item.count !== null && (
                <div className="text-[11px] text-slate-500 group-hover:text-indigo-600 font-mono mt-0.5">
                  {item.count} items
                </div>
              )}
            </button>
          ))}
        </div>
      </div>
    </div>
  );
};
